In [2]:
import pandas as pd
import numpy as np
import re
import seaborn as sns
import matplotlib.pyplot as plt
df = pd.read_csv("messy_data.csv")

df

,Customer_ID,Name,Email,Phone,City,Age,Purchase_Amount
0,101,Ankita Patil,ankita@gmail.com,98765 43210,pune,22,1500.0
1,102,Rahul Sharma,rahul@gmail.com,9876543210,Mumbai,25,2300.0
2,103,Priya Shah,priya@gmail,98765-43210,PUNE,abc,1800.0
3,104,Amit Kumar,amit@gmail.com,9876543210,mumbai,29,2100.0
4,105,Sneha Joshi,sneha @gmail.com,91234 56789,Pune,24,1700.0
5,106,Rohit Patil,rohit@gmail.com,+91-9876543210,Mumbai,27,2500.0
6,107,Neha Desai,neha@gmail.com,9876543210,pune,22,NaN
7,108,Vikas More,vikas@gmail.com,98765-43210,MUMBAI,31,3200.0
8,109,Pooja Patil,pooja@gmail.com,9876543210,Pune,28,1900.0
9,110,Kiran Jadhav,kiran@gmail.com,9876543210,Mumbai,abc,2200.0
10,111,Anjali Patil,anjali@gmail.com,9876543210,Pune,26,1600.0
11,112,Anjali Patil,anjali@gmail.com,9876543210,Pune,26,1600.0

In [3]:
df.head()

,Customer_ID,Name,Email,Phone,City,Age,Purchase_Amount
0,101,Ankita Patil,ankita@gmail.com,98765 43210,pune,22,1500.0
1,102,Rahul Sharma,rahul@gmail.com,9876543210,Mumbai,25,2300.0
2,103,Priya Shah,priya@gmail,98765-43210,PUNE,abc,1800.0
3,104,Amit Kumar,amit@gmail.com,9876543210,mumbai,29,2100.0
4,105,Sneha Joshi,sneha @gmail.com,91234 56789,Pune,24,1700.0

In [5]:
df.shape

(12, 7)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Customer_ID      12 non-null     int64
 1   Name             12 non-null     object
 2   Email            12 non-null     object
 3   Phone            12 non-null     object
 4   City             12 non-null     object
 5   Age              12 non-null     object
 6   Purchase_Amount  11 non-null     float64
dtypes: float64(1), int64(1), object(5)
memory usage: 804.0+ bytes

In [7]:
df.describe(include="all")

,Customer_ID,Name,Email,Phone,City,Age,Purchase_Amount
count,12.000000,12,12,12,12,12,11.000000
unique,NaN,11,11,5,8,9,NaN
top,NaN,Anjali Patil,anjali@gmail.com,9876543210,Pune,22,NaN
freq,NaN,2,2,7,4,2,NaN
mean,106.500000,NaN,NaN,NaN,NaN,NaN,2036.363636
std,3.605551,NaN,NaN,NaN,NaN,NaN,502.539008
min,101.000000,NaN,NaN,NaN,NaN,NaN,1500.000000
25%,103.750000,NaN,NaN,NaN,NaN,NaN,1650.000000
50%,106.500000,NaN,NaN,NaN,NaN,NaN,1900.000000
75%,109.250000,NaN,NaN,NaN,NaN,NaN,2250.000000
max,112.000000,NaN,NaN,NaN,NaN,NaN,3200.000000

In [8]:
df.isnull().sum()

Customer_ID        0
Name               0
Email              0
Phone              0
City               0
Age                0
Purchase_Amount    1
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df = df.drop_duplicates()

In [11]:
print("Rows after removing duplicates:", len(df))

Rows after removing duplicates: 12